### ISSUE TITLE
QEMU  installing

### ISSUE THREAD

**Issue by NikTrevor** [autoas/as#20]
Hi Parai,

I got this issue when installling QEMU for the first time (`scons run` after successfully building by `scons`).

Seem like a path problem. 

```
# MINGW_INSTALLS=mingw64 makepkg-mingw -sLf
==> Making package: mingw-w64-qemu 2.10.0-1 (Wed, May  1, 2019 12:18:21 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found qemu-2.10.0.tar.xz
==> Validating source files with sha256sums...
    qemu-2.10.0.tar.xz ... Passed
==> Extracting sources...
==> Starting prepare()...
make[1]: Entering directory '/d/Autosar_Project/as-master/com/as.tool/lua/device/websock'
Makefile:34: need modify the /c/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h line 2100/8474, add "FORCEINLINE" to each of the inline function
make[1]: Leaving directory '/d/Autosar_Project/as-master/com/as.tool/lua/device/websock'
scons: Reading SConscript files ...

scons: warning: Ignoring missing SConscript 'build/posix/SConscript'
File "/d/Autosar_Project/as-master/release/ascore/SConstruct", line 13, in <module>
TypeError: argument of type 'NoneType' is not iterable:
  File "/d/Autosar_Project/as-master/release/ascore/SConstruct", line 14:
    objs += SConscript('app/SConscript',variant_dir=bdir+'/app', duplicate=0)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/d/Autosar_Project/as-master/release/ascore/app/SConscript", line 15:
    if('CPLUSPLUS' in MODULES):
make: *** [Makefile:232: dep-canlib] Error 2
==> ERROR: A failure occurred in prepare().
    Aborting..
```

**Comment by parai** [comment]
Hi Nik:
Thanks for the issue report, fixed with commit https://github.com/autoas/as/commit/80e6981db4573f442d1362e7905e468f10075b36, please try with latest code.

**Comment by NikTrevor** [comment]
Thank Parai,
 
I have tried the new update, it seems better but eventually the error still occurs:

```
==> Starting prepare()...
make[1]: Entering directory '/c/Users/ttv/Desktop/AS_Update/as-master/com/as.tool/lua/device/websock'
Makefile:34: need modify the /c/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h line 2100/8474, add "FORCEINLINE" to each of the inline function
make[1]: Leaving directory '/c/Users/ttv/Desktop/AS_Update/as-master/com/as.tool/lua/device/websock'
scons: Reading SConscript files ...
INFO set GUI=xx, xx is one of GTK/SDL/OPENVG, defaut GTK
IndexError: list index out of range:
  File "/c/Users/ttv/Desktop/AS_Update/as-master/release/ascore/SConstruct", line 13:
    objs = SConscript('%s/com/SConscript'%(ASROOT),variant_dir=bdir, duplicate=0)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/c/Users/ttv/Desktop/AS_Update/as-master/com/SConscript", line 6:
    objs += SConscript('as.infrastructure/SConscript')
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/c/Users/ttv/Desktop/AS_Update/as-master/com/as.infrastructure/SConscript", line 15:
    objs = objs + SConscript(os.path.join(d, 'SConscript'))
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/c/Users/ttv/Desktop/AS_Update/as-master/com/as.infrastructure/arch/SConscript", line 10:
    objs += SConscript('%s/SConscript'%(ARCH))
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/c/Users/ttv/Desktop/AS_Update/as-master/com/as.infrastructure/arch/posix/SConscript", line 84:
    objs += SConscript('%s/com/as.tool/lua/SConscript'%(asenv['ASROOT']))
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/c/Users/ttv/Desktop/AS_Update/as-master/com/as.tool/lua/SConscript", line 11:
    objs +=  SConscript('can/SConscript')
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/c/Users/ttv/Desktop/AS_Update/as-master/com/as.tool/lua/can/SConscript", line 18:
    zlgcan = str(Glob('%s/CAN*'%(zlgcan_o))[0])
make: *** [Makefile:232: dep-canlib] Error 2
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by parai** [comment]
Hi Nik:
please check this page http://autoas.github.io/as/autosar/2018/02/20/as-study-platform.html, you should make sure that ZLG CAN lib folder just the same as picture shows, check the section 4.
Also, you can check the PKGBUILD, get to know how it works and fix the issues by yourself, even you can try disable ZLGCAN if you are not going to use it, but for how to disable it, you should check the Makefile and SConscripts, modify them to fulfill your requirement.
![pic](http://autoas.github.io/as/images/rewoa/third-party-can-folder-structure.png)
